### ISSUE TITLE
Write Function

### ISSUE THREAD

**Issue by skylin008** [MightyPork/PonyFrame#4]
Hi, Pls How to add the write function.If any demo to be test. Thanks!

**Comment by MightyPork** [comment]
i think something like this

```
def myWrite(bytes):
  pass

myInstance.write = myWrite
```

**Comment by skylin008** [comment]
Thanks. I wan to porting to micropython on openmv and pyboard.

**Comment by skylin008** [comment]
Hi, I had write the write functions as follow:
```
from pyb import UART
uart = UART(4, 9600)
def _write(buf):
    uart.write(buf)

class TinyFrame:
    def __init__(self, peer:int=1):
        self.write = _write # the writer function should be attached here

        self.id_listeners = {}
        self.type_listeners = {}
        self.fallback_listener = None
        self.peer = peer # the peer bit
```
Now the app file as: 

```
from pyb import UART

from tinyframe import TinyFrame

tf = TinyFrame(1)

buf = b'This is TinyFrame Test!\r\n'

uart = UART(4, 921600)

tf.send(1, buf, 1)

```
The error shows :
      Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
  File "tinyframe.py", line 144, in send
  File "tinyframe.py", line 135, in query
  File "tinyframe.py", line 163, in _compose
  File "tinyframe.py", line 127, in _pack
TypeError: function doesn't take keyword arguments
How to solve this issue.Thanks!

**Comment by MightyPork** [comment]
I don't know micropython and haven't used this library in two years, so i'm afraid you're on your own. All I can say is that it worked. Here's the project I made it for: https://git.ondrovo.com/gex/gex-client-py

**Comment by little-tesla** [comment]
In the repo there is now a simple serial port example which might help you. It's tested on Linux with Python 3.x.

**Comment by JLDohm** [comment]
It's been a minute, but the micropython and circuitpython implementation of int.to_bytes doesn't take a keyword argument, it takes a positional argument.

In _pack and _unpack I switched byteorder='big' to 'big' and it works.

**Comment by MightyPork** [comment]
> It's been a minute, but the micropython and circuitpython implementation of int.to_bytes doesn't take a keyword argument, it takes a positional argument.
> 
> In _pack and _unpack I switched byteorder='big' to 'big' and it works.

please make a PR, this can help other users
